format = "[┌──](line_color)[\\(](line_color)$username[](bold blue)$hostname[\\)](line_color)$directory$git_branch\n[└─](line_color)$character\n"
palette = "catppuccin_mocha"
right_format = "$all\n\n"
[character]
error_symbol = "[\\$](bold blue)"
success_symbol = "[\\$](bold blue)"

[directory]
format = "[─](line_color)[\\[](line_color)[$path]($style)[$read_only]($read_only_style)[\\]](line_color)"
style = "bold green"
truncation_length = 6
truncation_symbol = ".../"

[git_branch]
format = "[─](line_color)[\\[](line_color)[$symbol$branch(:$remote_branch)]($style)[\\]](line_color)"

[git_status]
disabled = true

[hostname]
format = "[$hostname]($style)[$ssh_symbol](peach)"
ssh_only = false
ssh_symbol = " 󰢹"
style = "bold blue"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
line_color = "#313244"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[shlvl]
disabled = false
symbol = "  "

[username]
format = "[$user]($style)"
show_always = true
style_user = "bold blue"
